# Generated by Django 4.0.4 on 2022-04-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50)),
                ('branch_id', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=18)),
                ('place', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'branch',
            },
        ),
    ]
