# Generated by Django 4.0.4 on 2022-04-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(default='Active', max_length=15),
        ),
    ]
