# Generated by Django 4.0.4 on 2022-04-25 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_branch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(default='requested', max_length=20)),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frombranch', to='adminapp.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.staff')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tobranch', to='adminapp.branch')),
            ],
            options={
                'db_table': 'transfer',
            },
        ),
    ]
