# Generated by Django 4.0.4 on 2022-04-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_staffbankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffbankdetails',
            name='branch',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='staffbankdetails',
            name='bank_name',
            field=models.CharField(max_length=150),
        ),
    ]
