# Generated by Django 4.0.4 on 2022-04-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_transfer'),
        ('adminapp', '0008_staffbankdetails_branch_and_more'),
    ]

    operations = [
    ]
