# Generated by Django 4.0.4 on 2022-04-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_merge_20220425_1659'),
        ('adminapp', '0009_merge_20220425_1701'),
    ]

    operations = [
    ]
