# Generated by Django 4.0.4 on 2022-05-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_merge_20220426_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='profile',
        ),
    ]
