# Generated by Django 4.0.4 on 2022-05-08 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_alter_staff_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=500)),
                ('transfer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapp.transfer')),
            ],
            options={
                'db_table': 'decline',
            },
        ),
    ]
