# Generated by Django 4.0.4 on 2022-04-23 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0005_branch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('purchase_cost', models.IntegerField()),
                ('selling_cost', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='BranchProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.product')),
            ],
            options={
                'db_table': 'branchproducts',
            },
        ),
    ]
