# Generated by Django 4.0.4 on 2022-04-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_customers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customers',
            table='customers',
        ),
    ]
