# Generated by Django 4.0.4 on 2022-04-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchproducts',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
