# Generated by Django 4.0.4 on 2022-04-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_customers_table'),
        ('branch', '0003_branchproducts_quantity'),
    ]

    operations = [
    ]
