# Generated by Django 4.0.4 on 2022-04-26 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_merge_20220426_1115'),
        ('branch', '0004_merge_20220423_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accholder_name', models.CharField(max_length=70)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=30)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.branch')),
            ],
            options={
                'db_table': 'branchBank',
            },
        ),
    ]
