# Generated by Django 4.0.4 on 2022-04-27 04:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_branchbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('reqdate', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='Requested', max_length=20)),
                ('avblbranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availablebranch', to='branch.branchproducts')),
                ('reqbranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedbranch', to='branch.branchproducts')),
            ],
            options={
                'db_table': 'medtransfer',
            },
        ),
    ]
