# Generated by Django 4.0.4 on 2022-04-27 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_merge_20220426_1115'),
        ('branch', '0006_medicinetransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinetransfer',
            name='reqbranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.branch'),
        ),
    ]
