# Generated by Django 4.0.4 on 2022-04-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0007_alter_medicinetransfer_reqbranch'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branchbank',
            table='branchbank',
        ),
    ]
