# Generated by Django 4.0.4 on 2022-04-29 04:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0008_alter_branchbank_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('payment_methode', models.CharField(max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.customers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branchproducts')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
