# Generated by Django 4.0.4 on 2022-04-29 06:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_merge_20220426_1115'),
        ('branch', '0008_alter_branchbank_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('note', models.CharField(max_length=500)),
                ('amount', models.FloatField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.branch')),
            ],
            options={
                'db_table': 'expense',
            },
        ),
    ]
