# Generated by Django 4.0.4 on 2022-04-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_merge_20220426_1115'),
        ('branch', '0009_invoive'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchproducts',
            unique_together={('product', 'branch')},
        ),
    ]
