# Generated by Django 4.0.4 on 2022-04-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0010_alter_branchproducts_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoive',
            name='invoice_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
