# Generated by Django 4.0.4 on 2022-04-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0010_branchbank_bankbalane'),
        ('branch', '0011_alter_invoive_invoice_no'),
    ]

    operations = [
    ]
