# Generated by Django 4.0.4 on 2022-04-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_merge_20220426_1115'),
        ('branch', '0013_invoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='invoice',
            new_name='Income',
        ),
    ]
