# Generated by Django 4.0.4 on 2022-04-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0012_alter_invoive_invoice_no'),
        ('branch', '0014_rename_invoice_income'),
    ]

    operations = [
    ]
