# Generated by Django 4.0.4 on 2022-05-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0015_merge_20220430_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoive',
            name='grand_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoive',
            name='gst',
            field=models.FloatField(default=0),
        ),
    ]
