# Generated by Django 4.0.4 on 2022-05-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0019_alter_expense_date_alter_income_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(default='Expense', max_length=10),
        ),
        migrations.AddField(
            model_name='income',
            name='income_type',
            field=models.CharField(default='Income', max_length=10),
        ),
    ]
